title = "Clever_Jimmy's Blog"
subtitle = ""
author = "Clever_Jimmy"
url = "https://leverimmy.top/"
language = "zh-CN"
avatar = "/gallery/misc/avatar.jpg"
github = "leverimmy"
email = "leverimmy@gmail.com"
motto = "No individual is isolated. He who is sad, saddens others."
since = 2022
icp = "京ICP备2024046776号-2"
gongan = "京公网安备11010802044639号"
gongan_id = "11010802044639"
permalink = ":year/:month/:day/:id/"
per_page = 10
source_dir = "content"
output_dir = "public"

[theme]
toc = true
code_theme = "InspiredGitHub"
accent_color = "#428bca"

[giscus]
repo = "leverimmy/My-Blog"
repo_id = "R_kgDOMbwQ2Q"
category = "Announcements"
category_id = "DIC_kwDOMbwQ2c4Cms0a"
